Add validation

diff --git a/.github/workflows/ci-init-script-check.yml b/.github/workflows/ci-init-script-check.yml
--- a/.github/workflows/ci-init-script-check.yml
+++ b/.github/workflows/ci-init-script-check.yml
@@ -59,9 +59,11 @@ jobs:
       run: du -hc ~/.gradle/caches/modules-2
     - name: Verify cleaned cache
       run: |
-        if [ -e ~/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-math3/3.1.1 ]; then
-          echo "Found commons-math3 3.1.1 in cache"
+        if [ ! -e ~/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-math3/3.1.1 ]; then
+          echo "::error ::Should find commons-math3 3.1.1 in cache"
+          exit 1
         fi
-        if [ ! -e ~/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-math3/3.1 ]; then
-          echo "Found commons-math3 3.1 NOT found in cache"
+        if [ -e ~/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-math3/3.1 ]; then
+          echo "::error ::Should NOT find commons-math3 3.1 in cache"
+          exit 1
         fi
